### PR TITLE
Code input/output/errors done for c and ruby

### PR DESCRIPTION
**Pull request by rishabhptr**
Removed gtimeout for now , would add timeout for all lang later.
Code input/output and errors output fixed for ruby/c.

TODO:
Clean up for 2-3 more languages.
Migrate UI settings from the other repo.

### CODE REVIEW

**Comment by namangupta01** [comment]
Is the code execution working?

**Comment by rishabhptr** [comment]
Yup code is running with input for c/ruby , errors go to log.txt and shown with compilation error would do for 3 more languages then would polish ui and deploy. Need to skip some features.

**Comment by namangupta01** [comment]
okay so should we merge this or you are going to add some more to this?

**Comment by rishabhptr** [comment]
Hmm I think I should complete for some more language and then merge so that we can do some UI next, so give me some time.

**Comment by namangupta01** [comment]
okay!!!

**Comment by rishabhptr** [comment]
Added execution logic for all 5 major languages but there is a bug , if I write correct code and run it , it will show output but if I put any error it doesnt show the error from log.txt . Please test this when you get time.

What I have done for these langauges is I have '<' piped input from tmp/input.txt , piped output to tmp/result.txt and if compile shows error write error stream '2>' to log.txt file.

**Comment by namangupta01** [comment]
so its good to merge now?

**Comment by rishabhptr** [comment]
Yes lets merge and try to fix that thing. It's definitely because of the ajax in javascript file as the error is going in log.txt just not displayed. Merge this and also add log.txt and a.out for gitignore as we dont want to track that.

**Pull request merged**
